---
- hosts: all

  vars:
    working_dir: "/vagrant"
    virtualenv_home: "/home/vagrant/.virtualenvs"

  tasks:
    - name: Install pre-requirements pkgs
      sudo: yes
      apt: pkg=python-pycurl

    - name: Add postgresql apt repo
      sudo: yes
      apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

    - name: Add postgresql apt key
      sudo: yes
      apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

    - name: Update apt-get
      sudo: yes
      apt: update_cache=yes

    - name: Install pkgs
      sudo: yes
      apt: pkg={{ item }} state=present
      with_items:
        - libpq-dev
        - postgresql-9.3
        - memcached
        - vim
        - redis-server
        - nano
        - python-dev
        - pkg-config
        - graphviz
        - libgraphviz-dev
        - libmemcached-dev
        - python-pip
        - build-essential

    # Setup PostgreSQL
    - name: Update pg_hba.conf
      sudo: yes
      copy: src=_files/pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres mode=0640
      notify:
        - Reload PostgreSQL

    - name: Update pip
      sudo: yes
      pip: name=pip state=latest

    - name: Install virtualenv
      sudo: yes
      pip: name=virtualenvwrapper

    - name: Add sourcing of virtualenvwrapper in bash profile
      lineinfile: dest="~/.profile" line="source /usr/local/bin/virtualenvwrapper.sh"

  handlers:
    - name: Reload PostgreSQL
      sudo: yes
      service: name=postgresql state=reloaded enabled=yes
