---
# tasks file for virtualenvwrapper
- name: install virtualenvwrapper
  pip: >
    name=virtualenvwrapper
    version={{ virtualenvwrapper_version }}
    state=present
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_installation

- name: set workon home (home for virtuaenvs)
  lineinfile: >
    dest={{ virtualenvwrapper_shell_rc_file }}
    regexp='export WORKON_HOME'
    line='export WORKON_HOME={{ virtualenvwrapper_venvs_home }}'
    state=present
    backup=yes
    create=yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_configuration

- name: load virtualenvwrapper script
  lineinfile: >
    dest={{ virtualenvwrapper_shell_rc_file }}
    regexp='source `which virtualenvwrapper.sh`'
    line='source `which virtualenvwrapper.sh`'
    state=present
    backup=yes
    create=yes
  tags:
    - virtualenvwrapper
    - virtualenvwrapper_configuration

