---
- hosts: all

  vars:
    working_dir: "/vagrant"

    # Stouts.timezone
    timezone_enabled: yes
    timezone_timezone: UTC

    # Stouts.ntp
    ntp_enabled: yes

    # Stouts.locale
    locale_enabled: yes
    locale_locales:
    - en_US.UTF-8

    # Stouts.python
    python_enabled: yes
    python_ppa: ppa:fkrull/deadsnakes
    python_versions: [2.7, 3.4]
    python_install: [
      'urllib3[secure]', 
      ipython, 
      ipdb, 
      virtualenvwrapper
    ]

    # Stouts.rabbitmq
    rabbitmq_enabled: yes
    rabbitmq_plugins:
    - rabbitmq_management
    rabbitmq_users:
    - user: admin
      password: admin
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      tags: administrator
    rabbitmq_vhosts: [default]
    rabbitmq_users_remove:
      - guest

    # Stouts.elasticsearch
    elasticsearch_enabled: yes
    elasticsearch_version: 2.4.1
    elasticsearch_download_url: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.1
    elasticsearch_network_host: 0.0.0.0
    # elasticsearch_plugins:
    # - name: lukas-vlcek/bigdesk
    # - name: elasticsearch/marvel

    # Stouts.kibana
    kibana_enabled: yes
    kibana_elasticsearch_url: http://{{elasticsearch_network_host}}:9200

    
    # Stouts.redis
    redis_enabled: yes
    redis_bind: 0.0.0.0
    redis_databases: 8

    # Stouts.apt
    apt_enabled: yes
    apt_default_packages:
      - redis-tools
      - git


    # ANXS.postgresql
    postgresql_version: 9.3
    postgresql_encoding: 'UTF-8'
    postgresql_locale: 'en_US.UTF-8'
    postgresql_admin_user: "postgres"
    postgresql_default_auth_method: "trust"
    postgresql_cluster_name: "main"
    postgresql_cluster_reset: false
    postgresql_databases:
    - name: default
      hstore: no
      uuid_ossp: no 
    postgresql_users:
    - name: vagrant
      pass: 
      encrypted: no
    postgresql_user_privileges:
    - name: vagrant
      db: default
      priv: "ALL"
      role_attr_flags: "CREATEDB"
    postgresql_pg_hba_default:
    - { type: local, database: all, user: 'all', address: '', method: '{{ postgresql_default_auth_method }}', comment: '' }
    - { type: local, database: all, user: all, address: '',             method: '{{ postgresql_default_auth_method }}', comment: '"local" is for Unix domain socket connections only' }
    - { type: host,  database: all, user: all, address: '127.0.0.1/32', method: '{{ postgresql_default_auth_method }}', comment: 'IPv4 local connections:' }
    - { type: host,  database: all, user: all, address: '::1/128',      method: '{{ postgresql_default_auth_method }}', comment: 'IPv6 local connections:' }


  pre_tasks:
    - name: Update apt-get
      become: true
      apt: update_cache=yes


  roles:
    - { role: Stouts.timezone, become: true }
    - { role: Stouts.ntp, become: true }
    - { role: Stouts.locale, become: true }
    - { role: Stouts.python, become: true }
    - { role: Stouts.rabbitmq, become: true }
    - { role: Stouts.redis, become: true }
    - { role: Stouts.elasticsearch, become: true }
    - { role: Stouts.kibana, become: true }
    - { role: Stouts.apt, become: true }
    - { role: ANXS.postgresql, become: true }


  post_tasks:
    - name: Add sourcing of virtualenvwrapper in bash profile
      lineinfile: dest="~/.profile" line="source /usr/local/bin/virtualenvwrapper.sh"
