---
- hosts: all

  vars:
    working_dir: "/vagrant"
  
    # Stouts.timezone
    timezone_enabled: yes
    timezone_timezone: UTC

    # Stours.ntp
    ntp_enabled: yes

    # Stouts.locale
    locale_enabled: yes
    locale_locales:
    - en_US.UTF-8

    # Stouts.python
    python_enabled: yes
    python_ppa: ppa:fkrull/deadsnakes
    python_versions: [2.7]
    python_install: [ipython, ipdb, virtualenvwrapper]
    python_virtualenvs:
    - path: /home/vagrant/.virtualenvs

    # Stouts.rabbitmq
    rabbitmq_enabled: yes
    rabbitmq_plugins:
    - rabbitmq_management
    rabbitmq_users:
    - user: admin
      password: admin
      vhost: /
      configure_priv: .*
      read_priv: .*
      write_priv: .*
      tags: administrator
    rabbitmq_vhosts: []



  pre_tasks:
    - name: Update apt-get
      sudo: yes
      apt: update_cache=yes

  
  roles:
    - { role: Stouts.timezone, sudo: yes }
    - { role: Stouts.ntp, sudo: yes }
    - { role: Stouts.locale, sudo: yes }
    - { role: Stouts.python, sudo: yes }
    - { role: Stouts.rabbitmq, sudo: yes }
